version: '3.9'
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/14
          gateway: 172.20.0.1

services:
  backend:
    image: ptdat11/dev-env:latest
    container_name: backend-cs
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/home/backend
    depends_on:
      - pgsql
    networks:
      backend:
        ipv4_address: 172.20.0.3
  pgsql:
    image: postgres:latest
    container_name: pgsql-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dat
      - POSTGRES_PASSWORD=for-Thu
      - POSTGRES_DB=db
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 172.20.0.2